### ISSUE TITLE
기본 페이지 변경 요청

### ISSUE THREAD

**Issue by LK999** [sokkanji/createPortal-vs-dialog-element#1]
next.config.js에서 basePath가 'createPortal-vs-dialog-element'으로 설정되어 있습니다.

루트 페이지가 아닐 이유가 없을 것 같은데, basePath를 '/.'이나 default 설정으로 바꾸는게 좋을 것 같습니다.

**Comment by sokkanji** [comment]
github pages 배포 경로가 '/createPortal-vs-dialog-element' 라서 basePath 설정을 해두었습니다.
확인해주셔서 감사합니다!
